package:
  name: "pytessel"
  version: "0.1.3.0"

source:
  path: .

requirements:
  build:
    - numpy
    - python {{ python }}

  host:
    - pip
    - python
    - setuptools
    - cython
    - numpy >=1.17

  run:
    - python
    - numpy >=1.17

test:
  requires:
    - numpy >=1.17
    - setuptools
    - pytest
  source_files:
    - tests/*.py
  commands:
    - pytest tests

about:
  home: https://github.com/ifilot/pytessel
  license: GPL3
  license_family: GPL
  summary: Python package for building isosurfaces from 3D scalar fields
  description: See the package README.md for more information.
