[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython",
    "numpy",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-requires = "pytest numpy cython"
test-command = "pytest {project}/tests"

# skip PyPy wheels
skip = ["pp*", "cp36-*"]
