name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - name: Install dependencies
      run: |
        yum -y install eigen3-devel boost-devel libgomp glm-devel
        yum -y install mlocate
        yum -y install gcc
        ls -alh /opt/python/cp*
        /opt/python/cp37-cp37m/bin/python -m pip install numpy tqdm cython pytest
        /opt/python/cp38-cp38/bin/python -m pip install numpy tqdm cython pytest
        /opt/python/cp39-cp39/bin/python -m pip install numpy tqdm cython pytest
        /opt/python/cp310-cp310/bin/python -m pip install numpy tqdm cython pytest
        /opt/python/cp311-cp311/bin/python -m pip install numpy tqdm cython pytest
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Build
      run: ./deploy/docker_setup_github.sh
    - name: Test
      run: ./deploy/docker_test_github.sh

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - shell: bash -l {0}
        run: |
          echo $PATH
          echo $INCLUDE
          echo $LIB
          conda info
          conda list
          conda build .
